### ISSUE TITLE
Completion status returning false on complete

### ISSUE THREAD

**Issue by LJBowen** [kaandedeoglu/KDCircularProgress#23]
I create a CircularProgress at on button press. I than send off a GET request and if I am animating when I finish with my request I pause and set a new animateFromAngle to complete in 1 second. I appears that doing this is causing the completed to return false in the new animeFromAngle.

**Comment by dfusilier** [comment]
Also having this problem.

**Comment by kaandedeoglu** [comment]
This should be solved with the latest version of the library. Can you please try and confirm?

**Comment by kaandedeoglu** [comment]
Closing this due to the inactivity. Feel free to reopen if the problem persists.

**Comment by LJBowen** [comment]
Sorry, I have been busy working on another project. It appears to still occur. I've also noticed that if i call animate(toAngle) while another animation is occurring that is returning false for completed.

**Comment by kaandedeoglu** [comment]
@LJBowen This is the intended behavior. The completed argument is true only if the animation ends on its own. You can use it to implement your completion logic. Please also see #47

**Comment by LJBowen** [comment]
@kaandedeoglu Thanks!
